#%RAML 1.0 NamedExample
Questionset:
  [
 {
 "question_type": "Anxiety",
 "question_number": "1",
 "question": "Feeling nervous, anxious, or on edge?",
 "op_1": "Not at all",
 "op_2": "Several Days",
 "op_3": "More than half the days",
 "op_4": "Nearly every day"
 },

 {
 "question_type": "Anxiety",
 "question_number": "2",
 "question": "Not being able to stop or control worrying?",
 "op_1": "Not at all",
 "op_2": "Several Days",
 "op_3": "More than half the days",
 "op_4": "Nearly every day"
 },

 {
 "question_type": "Anxiety",
 "question_number": "3",
 "question": "Worrying too much about different things?",
 "op_1": "Not at all",
 "op_2": "Several Days",
 "op_3": "More than half the days",
 "op_4": "Nearly every day"
 }
  ]