#%RAML 1.0 NamedExample
UserUpdate:
   {   
     "Name":"alagar",
     "age":19,
     "gender":"male",
      "location":"theni",
      "mobileNumber":"9600291731",
      "email":"kiran123@gmail.com",
      "password":"Kiran@123",
      "confirmPassword":"Kiran@123",
      "id":"1",
      "status":"updated successfully"
  }